config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user ,lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: "questions#index"

  concern :voitingable do
    member do
      post :like
      post :dislike
    end
  end

  resources :questions, concerns: [:voitingable] do
    resources :comments, only: [:create]

    resources :answers, shallow: true, concerns: [:voitingable], only: [:create, :update, :destroy] do
      member { post :best }

      resources :comments, only: [:create]
    end
    
    # member { get :subscribe }
    # member { get :unsubscribe }
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :attach_files, only: [:destroy]
  resources :links, only: [:destroy]
  resources :rewards, only: [:index]
  
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :index, on: :collection
      end
      
      resources :questions, only: [:index, :show, :destroy, :create, :update] do
        resources :answers, only: [:index, :show, :destroy, :create, :update], shallow: true
      end
    end
  end

  get '/search', to: 'search_engines#search'
  
  mount ActionCable.server => "/cable"
end

app/models/question.rb
class Question < ApplicationRecord
  include Voitingable
  
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  has_many :comments, as: :commentable,  dependent: :destroy
  has_many :subscription, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true
  after_create :calculate_reputation

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [:show, :destroy] #, :update

  authorize_resource
  def index
    @questions = Question.all

    render json: @questions
  end

  def show
    render json: @question, inlcude: [:comments, :links, :files] 
  end

  def create
    @question = current_resource_owner.authored_questions.build(question_params)
    if @question.save
      render json: @question
    else
      render json: { created_status: "The question was not created"}
    end    
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    render json: @question
  end

  private
  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voitinged
  
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: %i[show edit update destroy subscribe unsubscribe]
  after_action :publish_question, only: [:create]

  before_action :gon_question, only: [:show]

  authorize_resource
  
  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
    @subscription = Subscription.find_by(user_id: current_user.id, question_id: @question.id) if current_user
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit
    # unless @question.reward
    #   @question.build_reward
    # end
    # render partial: "edit"
  end

  def create
    @question = current_user.authored_questions.build(question_params)
    if @question.save
      Subscription.create!(user_id: current_user.id, question_id: @question.id)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private
  def gon_question
    gon.question_id = @question.id
  end
  
  def publish_question
    return if @question.errors.any?
    
    files = {}
    @question.files.each_with_index do |f, index|
      file = Hash.new
      file[:id] = f.id
      file[:file_name] = f.filename.to_s
      file[:file_url] = rails_blob_path(f, only_path: true)
      files[index] = file
    end

    links = {}
    @question.links.each_with_index do |l, index|
      link = Hash.new
      link[:id] = l.id
      link[:name] = l.name
      link[:url] = l.url
      links[index] = link
    end

    reward = {}
    if @question.reward
      reward[:id] = @question.reward.id
      reward[:name] = @question.reward.name
      reward[:url_file] = rails_blob_path(@question.reward.file, only_path: true)
    end
    renderer = ApplicationController.renderer_with_signed_in_user(current_user)

    ActionCable.server.broadcast(
      'questions',
      renderer.render(
        json: { id: @question.id,
                title: @question.title,
                body: @question.body, 
                files: files,
                links: links,
                reward: reward
              }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                      links_attributes: [:id, :name, :url],
                                      reward_attributes: [:name, :file],
                                      comment_attributes: [:body] )
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
div class="nested-fields form-group"
  .field
    = f.label :name, 'Link name'
    = f.text_field :name, class: "form-control"
  .field
    = f.label :url
    = f.text_field :url, class: "form-control"
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
div id="question-#{question.id}" class="d-flex flex-column w-100 my-2 p-1 bg-light"
  div class="question-title text-center"
    h4= question.title
  div class="d-flex flex-row justify-content-between"
    div class="question-body w-70"
      p= question.body

  div class="additional material d-flex flex-row justify-content-around"
    .attached-files
      = render 'shared/attach_file', resource: question
      
    .links-question
      = render 'shared/show_links', resource: question    

  div class="question-action w-30 d-flex flex-row justify-content-end"
    div  
      = link_to question_path(question), class: 'bi bi-eye-fill mx-1', data_toggle: "tooltip", title: "Show question"
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
          <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
        </svg>
    
    div class="raiting-#{question.id}"
      = question.sum_raiting

    -if can?(:destroy, question)
      div
        = link_to '#', class: 'edit-question-link bi bi-pen-fill mx-1', data: { question_id: question.id }, data_toggle: "tooltip", title: "Edit question"
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
          </svg>
      div  
        = link_to question_path(question), class: 'bi bi-trash-fill mx-1', method: :delete, data: { confirm: 'You are sure' }, data_toggle: "tooltip", title: "Delete question"
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
          </svg>
                            
    -if can?(:like, question)
      div
        = link_to like_question_path(question), class: 'bi bi-hand-thumbs-up-fill mx-1', method: :post, remote: true, data_toggle: "tooltip", title: "Like"
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
            <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
          </svg>
                
      div
        = link_to dislike_question_path(question), class: 'bi bi-hand-thumbs-down-fill mx-1', method: :post, remote: true, data_toggle: "tooltip", title: "Dislike"
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 16 16">
            <path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
          </svg>     

  div id="div-edit-question-#{question.id}"
    = form_with model: question, class: 'form-group hidden', local: false, html: { id: "edit-question-#{question.id}" } do |f|
      div class="d-flex flex-column w-100"
        div class="p-2"
          = f.label :title, 'Title question'
          = f.text_field :title, class: "form-control m-1"
          = f.label :body, 'Body question'
          = f.text_area :body, class: "form-control m-1"
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true, class: "form-control m-1"
        
        div class="p-2"
          h6= "Reward:"
          = f.fields_for :reward do |r|
            = r.label :name, 'Name reward'
            = r.text_field :name, class: "form-control"
            = r.label :file
            = r.file_field :file, direct_upload: true, class: "form-control"

        div class="p-2"
          h6= "Links:"
          #links
            = f.fields_for :links do |link|
              = render 'link_fields', f: link
            .links
              = link_to_add_association 'add link', f, :links

        div class="p-2"
          = f.submit 'Update', class: "btn btn-primary w-100" 

app/views/questions/edit.html.slim
/ = form_with model: @question, class: 'form-group hidden', local: false, html: { id: "edit-question-#{@question.id}" } do |f|
/   div class="d-flex flex-column w-100"
/     div class="p-2"
/       = f.label :title, 'Title question'
/       = f.text_field :title, class: "form-control m-1"
/       = f.label :body, 'Body question'
/       = f.text_area :body, class: "form-control m-1"
/       = f.label :files
/       = f.file_field :files, multiple: true, direct_upload: true, class: "form-control m-1"
    
/     div class="p-2"
/       h6= "Reward:"
/       = f.fields_for :reward do |r|
/         = r.label :name, 'Name reward'
/         = r.text_field :name, class: "form-control"
/         = r.label :file
/         = r.file_field :file, direct_upload: true, class: "form-control"

/     div class="p-2"
/       h6= "Links:"
/       #links
/         = f.fields_for :links do |link|
/           = render 'link_fields', f: link
/         .links
/           = link_to_add_association 'add link', f, :links

/     div class="p-2"
/       = f.submit 'Update', class: "btn btn-primary w-100" 

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  .questions
    -if can?(:create, Question)
      div class="new-question-link"
        = link_to 'Ask', new_question_path

      div class="question-errors"
        = render 'shared/errors', resource: @question

    - if @questions
      = render @questions
         

app/views/questions/new.html.slim
div class="border p-1 bg-light"
  = render 'shared/errors', resource: @question

  = form_with model: @question, class: "form-group" do |f|
    div class="d-flex w-100"
      div class="p-2"
        = f.label :title
        = f.text_field :title, class: "form-control"
        = f.label :body
        = f.text_area :body, class: "form-control"
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"

      div class="p-2"
        div id="reward"
          h4 class="text-center"
            = "Reward:"
          = f.fields_for :reward do |r|
            = r.label :name, 'Name reward'
            = r.text_field :name, class: "form-control"
            = r.label :file
            = r.file_field :file, direct_upload: true, class: "form-control"

      div class="p-2"
        div id="links"
          h4 class="text-center"
            = "Links:"
          = f.fields_for :links do |link|
            = render 'link_fields', f: link
          .links
            = link_to_add_association 'add link', f, :links
          / small class="text-center text-danger"
          /   = "The link to the gist should be of the format: 'https://gist.github.com/user_name/4eac......75.js'" 

    p
      = f.submit 'Ask question', class: 'btn btn-primary w-100'

app/views/questions/show.html.slim
- cache @question do
  div class="question-show w-100 bg-light" id="question-#{@question.id}"
    div class="d-flex flex-column"
      div class="d-flex flex-row p-2 justify-content-center"
        div class="question-title "
          h2 = @question.title
        div class="subscribes"
          -if current_user&.subscribed?(@question)
            = link_to subscription_path(@subscription), method: :delete, remote: true, class: 'bi bi-bell-slash-fill', data_toggle: "tooltip", title: "Unsubscribe"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-slash-fill" viewBox="0 0 16 16">
                <path d="M5.164 14H15c-1.5-1-2-5.902-2-7 0-.264-.02-.523-.06-.776L5.164 14zm6.288-10.617A4.988 4.988 0 0 0 8.995 2.1a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 7c0 .898-.335 4.342-1.278 6.113l9.73-9.73zM10 15a2 2 0 1 1-4 0h4zm-9.375.625a.53.53 0 0 0 .75.75l14.75-14.75a.53.53 0 0 0-.75-.75L.625 15.625z"/>
              </svg>                                            
          -elsif current_user
            = link_to subscriptions_path(question_id: @question.id), method: :post, remote: true, class: 'bi bi-bell-fill', data_toggle: "tooltip", title: "Subscribe"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
              </svg> 
      div
        p class="body-question p-2"
          = @question.body
                        
      div class="additional material d-flex flex-row justify-content-around"
        div class="attached-files" 
          = render 'shared/attach_file', resource: @question
        div class="links-question"
          = render 'shared/show_links', resource: @question

      div class="reward text-center"
        - if @question.reward
          h6= "Reward: #{@question.reward.name}"
          = image_tag(url_for(@question.reward.file) )

      div class="comments-question text-center"
        h3= "Comments for question"
        - if @question.comments && current_user
          = render @question.comments

      div class="comment-question-new"
        .question-comment-errors
        - if current_user
          = render 'shared/new_comment', resource: @question

    div class="answers" id="answers"
      div class="text-center"
        h3= "Answers:"
      - if @question.answers
        = render @question.answers

    div class="div-new-answer p-2"
      h3 class="text-center"
        ="New Answer" 
      .answer-errors
        = render 'shared/errors', resource: @answer
      div
        = render 'answers/new', resource: @question

app/views/questions/subscribe.js.erb
alert("Vi podpisalis' na vopros")

app/views/questions/unsubscribe.js.erb
alert("Vi otpisalis' ot voprosa")

app/views/questions/update.js.erb
<% if flash[:alert] %>
  <% flash.each do |key, value| %>
    $('.msg-alert').delay(1000).html("<%= value %>")
  <% end %>
<% end %>

$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $(".questions #question-<%= @question.id %>").html('<%= j render @question %>');
<% end %>