config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user ,lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: "questions#index"

  concern :voitingable do
    member do
      post :like
      post :dislike
    end
  end

  resources :questions, concerns: [:voitingable] do
    resources :comments, only: [:create]

    resources :answers, shallow: true, concerns: [:voitingable], only: [:create, :update, :destroy] do
      member { post :best }

      resources :comments, only: [:create]
    end
    
    # member { get :subscribe }
    # member { get :unsubscribe }
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :attach_files, only: [:destroy]
  resources :links, only: [:destroy]
  resources :rewards, only: [:index]
  
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :index, on: :collection
      end
      
      resources :questions, only: [:index, :show, :destroy, :create, :update] do
        resources :answers, only: [:index, :show, :destroy, :create, :update], shallow: true
      end
    end
  end

  get '/search', to: 'search_engines#search'
  
  mount ActionCable.server => "/cable"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user
  def initialize(user)
    @user = user
    if user 
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :create, [Question, Answer, Comment]
    can [:update, :destroy], [Question, Answer, Comment], author_id: user.id

    can [:like, :dislike], [Question, Answer] do |resource|
      !user.author_of?(resource)
    end

    cannot [:like, :dislike], [Question, Answer], author_id: user.id

    can :best, Answer do |answer|
      user.author_of?(answer.question)
    end

    can :destroy, ActiveStorage::Attachment do |file|
      user.author_of?(file.record)
    end

    can :destroy, Link do |link|
      user.author_of?(link.linkable)
    end

    can :index, Reward, id: user.id

    can [:me, :index], User, id: user.id

    can [:destroy], Api::V1::QuestionsController, id: user.id

    can [:create], Subscription

    can [:destroy], Subscription do |subscription|
      subscription.subscriber?(user)
    end

    can [:search], [Answer, Question, Comment, User], id: user.id
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voitingable
  
  belongs_to :question, touch: true
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, as: :commentable,  dependent: :destroy
  
  has_many_attached :files
  
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_answer_to_author_question_and_subscribers

  def choose_best_answer
    transaction do
      question.answers.where(best: true).update(best: false)
      self.update!(best: true)
      question.reward.update(user_id: self.author.id ) if question.reward
    end
  end

  private 
  def send_answer_to_author_question_and_subscribers
    SendAnswerJob.perform_later(self)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id
  
  belongs_to :commentable, polymorphic: true, touch: true
  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true
  
  validates :name, :url, presence: true
  validates :url, format: URI::regexp(%w[http https])
end

app/models/question.rb
class Question < ApplicationRecord
  include Voitingable
  
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  has_many :comments, as: :commentable,  dependent: :destroy
  has_many :subscription, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true
  after_create :calculate_reputation

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true
  
  has_one_attached :file

  validates :name, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
  
  validates_uniqueness_of :user_id, scope: :question_id

  def subscriber?(user)
    self.user_id == user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authored_answers, class_name: 'Answer', foreign_key: :author_id
  has_many :authored_questions, class_name: 'Question', foreign_key: :author_id
  has_many :voitings
  has_many :comments
  has_many :subscription, dependent: :destroy

  has_many :authorizations, dependent: :destroy
  
  has_many :rewards, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github, :facebook]

  def author_of?(resource)
    self.id == resource.author_id
  end

  def self.find_for_oauth(auth)
    MyServices::FindForOauth.new(auth).call
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  def subscribed?(question)
    Subscription.find_by(user_id: self.id, question_id: question.id) ? true : false
  end
end

app/models/voiting.rb
class Voiting < ApplicationRecord
  belongs_to :user
  belongs_to :voitingable, polymorphic: true
  
  validates :user_id, uniqueness: { scope: [ :voitingable_type, :voitingable_id ] }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :load_link, only: [:destroy]
  authorize_resource

  def destroy
    if current_user.author_of?(@model)
      @link.destroy
    else
      flash[:notice] = "Only author can delete the link for the question!"
    end
  end

  private
  def load_link
    @link = Link.find(params[:id])
    load_link_model
  end

  def load_link_model
    @model = @link.linkable
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/search_engines_helper.rb
module SearchEnginesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'answers', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'questions', 'data-turbolinks-track': 'reload'

  body class="container"
    = render 'shared/header'
    div class="notice"
      = notice
    div class="msg-alert"
      = alert
    = render 'shared/search'
    div class="d-flex justify-content-center"
      = yield

app/views/shared/_attach_file.html.slim
- if resource.files.attached?
  h6= "Attached files:" 
  - resource.files.each do |file|
    p
      = link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(resource)
        = link_to attach_file_path(file), method: :delete, data: { confirm: 'Are you sure?'  }, class: 'bi bi-trash-fill mx-1', data_toggle: "tooltip", title: "Delete file"
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
          </svg>  
          

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} errors(s) detected: "
  ul 
    -resource.errors.full_messages.each do |message|
      li= message 

app/views/shared/_header.html.slim
nav class="navbar navbar-light bg-light d-flex-inline"
  div class="p-2"
    = link_to "QnA", questions_path, class: "navbar-brand"
  div class="p-2"
    - if current_user 
      = current_user.email
      = link_to 'View my rewards', rewards_path, class: "mx-2 btn btn-success btn-sm"
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm"
    - else
      = link_to 'Sign in', new_user_session_path, class: "btn btn-secondary mx-2 btn-sm"
      = link_to 'Sign up', new_user_registration_path, class: "btn btn-secondary btn-sm"

app/views/shared/_new_comment.html.slim
- cache resource do
  div class="px-4 text-center"
    = form_with model: [resource, Comment.new], local: false, class: 'new-comment form-group' do |f|
      = f.hidden_field :commentable, value: resource.class.name
      = f.label :body
      = f.text_area :body, class: "form-control"
      -if resource.class.to_s == "Question" 
        = f.submit "Add Comment to Question", class: 'btn btn-primary btn-sm w-75 my-2'
      -else
        = f.submit "Add Comment to Answer", class: 'btn btn-primary btn-sm w-75 my-2' 

app/views/shared/_search.html.slim
= form_tag(search_path, method: :get, class: 'form-group') do
  div class="search d-flex flex-row justify-content-end p-2"
      div class="mx-1"
        = text_field_tag :search, params[:search], class: "form-control form-control-sm" 
      div
        = select_tag "find", options_for_select([ "Questions", "Answers", "Users", "Comments", "All" ], "All"), class: "form-control form-control-sm"
      div class="mx-1"
        = submit_tag "Search", class: 'btn btn-sm btn-primary'

app/views/shared/_show_links.html.slim
-if !resource.links.blank?
  h6= "Links:"
  - resource.links.each do |link|
    - if link.url.include? "https://gist"
      div id="link-#{link.id}"
        div class="d-flex flex-row"
          div
            = javascript_include_tag link.url
          div
            - if current_user&.author_of?(resource)
              = link_to link_path(link), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, id: "delete-link-#{link.id}", class: "bi bi-trash-fill mx-1 delete-link-#{link.id}", data_toggle: "tooltip", title: "Delete link"
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                  <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>                            
                        
    - else
      div id="link-#{link.id}"
        = link_to link.name, link.url
        - if current_user&.author_of?(resource)
          = link_to link_path(link), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, id: "delete-link-#{link.id}", class: "bi bi-trash-fill mx-1", data_toggle: "tooltip", title: "Delete link"                                                                    
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
              <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
            </svg> 