config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user ,lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: "questions#index"

  concern :voitingable do
    member do
      post :like
      post :dislike
    end
  end

  resources :questions, concerns: [:voitingable] do
    resources :comments, only: [:create]

    resources :answers, shallow: true, concerns: [:voitingable], only: [:create, :update, :destroy] do
      member { post :best }

      resources :comments, only: [:create]
    end
    
    # member { get :subscribe }
    # member { get :unsubscribe }
  end

  resources :subscriptions, only: [:create, :destroy]

  resources :attach_files, only: [:destroy]
  resources :links, only: [:destroy]
  resources :rewards, only: [:index]
  
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :index, on: :collection
      end
      
      resources :questions, only: [:index, :show, :destroy, :create, :update] do
        resources :answers, only: [:index, :show, :destroy, :create, :update], shallow: true
      end
    end
  end

  get '/search', to: 'search_engines#search'
  
  mount ActionCable.server => "/cable"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voitingable
  
  belongs_to :question, touch: true
  belongs_to :author, class_name: "User", foreign_key: :author_id
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, as: :commentable,  dependent: :destroy
  
  has_many_attached :files
  
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_answer_to_author_question_and_subscribers

  def choose_best_answer
    transaction do
      question.answers.where(best: true).update(best: false)
      self.update!(best: true)
      question.reward.update(user_id: self.author.id ) if question.reward
    end
  end

  private 
  def send_answer_to_author_question_and_subscribers
    SendAnswerJob.perform_later(self)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voitinged
  
  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:destroy, :update, :best]

  after_action :publish_answer, only: [:create]
  
  authorize_resource

  def create
    @answer = @question.answers.build(answer_params)
    @answer.author = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def best
    @answer.choose_best_answer
    flash[:alert] = "The best answer was chosen"
  end

  private
  def load_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                    links_attributes: [:id, :name, :url] )
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?

    files = {}
    @answer.files.each_with_index do |f, index|
      file = Hash.new
      file[:id] = f.id
      file[:file_name] = f.filename.to_s
      file[:file_url] = rails_blob_path(f, only_path: true)
      files[index] = file
    end

    links = {}
    @answer.links.each_with_index do |l, index|
      link = Hash.new
      link[:id] = l.id
      link[:name] = l.name
      link[:url] = l.url
      links[index] = link
    end
    renderer = ApplicationController.renderer_with_signed_in_user(current_user)

    ActionCable.server.broadcast(
      "answers_#{@question.id}",
      renderer.render(
        json: { id: @answer.id,
                body: @answer.body,
                voitings: @answer.voitings,
                links: links,
                files: files,
                question_user_id: @answer.question.author.id
        }
      )
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: [:show, :destroy]
  
  authorize_resource
  def index
    @answers = @question.answers
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.author = current_resource_owner
    @answer.save    
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
    render json: @answer
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end
  
  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)   
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div class="d-flex flex-column" id="answer-#{answer.id}"
  -if answer.persisted?
    - cache answer do
      div class="d-flex flex-row justify-content-arround"
        div class="answer-body p-2" 
          p= answer.body
        
        div class="raiting-#{answer.id}"
          = answer.sum_raiting

      div class="additional material d-flex flex-row justify-content-around"
        .attached-files
          = render 'shared/attach_file', resource: answer
        .links-answer
          = render 'shared/show_links', resource: answer 

      div class="answer-action d-flex flex-row justify-content-end mr-2"  
        -if can?(:destroy, answer)
          div
            = link_to '#', class: 'edit-answer-link bi bi-pen-fill mx-1', data: { answer_id: answer.id }, data_toggle: "tooltip", title: "Edit answer"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
              </svg>
          div     
            = link_to answer_path(answer), class: "bi bi-trash-fill mx-1", method: :delete, data: { answer_id: answer.id, confirm: 'You are sure' }, remote: true, data_toggle: "tooltip", title: "Delete answer"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
              </svg>                              
                              
                              
        -if can?(:best, answer)
          div
            = link_to best_answer_path(answer), class: 'best-answer-link bi bi-heart-fill mx-1', method: :post, remote: true, data_toggle: "tooltip", title: "Best answer"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
              </svg>                                
                                
        -if can?(:like, answer)
          div
            = link_to like_answer_path(answer), method: :post, remote: true, class: 'bi bi-hand-thumbs-up-fill mx-1', data_toggle: "tooltip", title: "Like"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
              </svg>                  
                  
          div         
            = link_to dislike_answer_path(answer), method: :post, remote: true, class: 'bi bi-hand-thumbs-down-fill mx-1', data_toggle: "tooltip", title: "Dislike"
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 16 16">
                <path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
              </svg>  

      div
        = form_with model: answer, local: false, class: ' form-group hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
          div class="d-flex flex-column w-100"
            div class="p-2"
              = f.label :body, 'Your answer'
              = f.text_area :body, class: "edit-answer-textarea form-control"
              = f.label :files
              = f.file_field :files, multiple: true, direct_upload: true, class: "form-control" 
            
            div class="p-2"
              p Links:
              #links
                = f.fields_for :links do |link|
                  = render 'link_fields', f: link
                .links
                  = link_to_add_association 'add link', f, :links
            div class="p-2"
              = f.submit 'Save Answer', class: "btn btn-primary w-100"

      div
        div class="comments-answer text-center"
          h3= "Comments for answer"
          - if answer.comments && current_user
            = render answer.comments

      div class="comment-answer-new"
      .answer-comment-errors
      - if current_user
        = render 'shared/new_comment', resource: answer

app/views/answers/_link_fields.html.slim
div class="nested-fields form-group" 
  .field
    = f.label :name, 'Link name'
    = f.text_field :name, class: "form-control"
  .field
    = f.label :url
    = f.text_field :url, class: "form-control"
  = link_to_remove_association "remove link", f

app/views/answers/_new.html.slim
= form_with model: [@question, @answer], local: false, class: 'new-answer form-group' do |f|
  = f.label :body
  = f.text_area :body, class: "form-control"
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true, class: "form-control"

  div id="links" class="links-answer-new"
    h6 class="mt-2"
      = "Links:"
    = f.fields_for :links do |link|
      = render 'link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links
    
  = f.submit 'Reply', class: "btn btn-primary w-100"

app/views/answers/best.js.erb
<% if flash[:alert] %>
  <% flash.each do |key, value| %>
    $('.msg-alert').delay(1000).html("<%= value %>")
  <% end %>
<% end %>

var parentElement = document.getElementById('answers');
var first_answer = parentElement.firstChild;
var best_answer = document.getElementById("answer-<%= @answer.id%>");
parentElement.insertBefore(best_answer, first_answer);

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$(".answers #answer-<%= @answer.id %>").remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>